// Generated by save-db.php on 2025-10-21T07:44:50+00:00
var controlDatabase = {
    "1": {
        "desc": "วายริ่งชุด LAMP+FUSE(3เฟส)",
        "price": 500
    },
    "2": {
        "desc": "วายริ่งชุด AMP+CT+SELECTOR",
        "price": 500
    },
    "3": {
        "desc": "วายริ่งชุด LAMP+FUSE+AMP+CT+VOLT+SELECTOR",
        "price": 500
    },
    "4": {
        "desc": "วายริ่งชุด Hz,PF,Hr มิเตอร์",
        "price": 500
    },
    "5": {
        "desc": "วายริ่งชุด Kw,Kwh มิเตอร์",
        "price": 500
    },
    "6": {
        "desc": "วายริ่งชุด LAMP+FUSE+DIGITALMETER+CT",
        "price": 500
    },
    "7": {
        "desc": "ติดตั้งอุปกรณ์ชุด CONTROL CAP(ใช้เพลท STOCK)",
        "price": 500
    },
    "8": {
        "desc": "วายริ่งชุด CONTROL CAP(PFC) 6 STEP",
        "price": 500
    },
    "9": {
        "desc": "วางยริ่งชุด CONTROL CAP (PFC) 8 STEP",
        "price": 500
    },
    "10": {
        "desc": "วายริ่งชุด CONTROL CAP (PFC) 10 STEP",
        "price": 500
    },
    "11": {
        "desc": "วายริ่งชุด CONTROL CAP (PFC) 12 STEP",
        "price": 500
    },
    "12": {
        "desc": "วายริ่งชุด CONTROL CAP 6 STEP AUTO ไม่มี PUSH BUTTON",
        "price": 500
    },
    "13": {
        "desc": "วายริ่งชุด CONTROL CAP 12 STEP AUTO ไม่มี PUSH BUTTON",
        "price": 500
    },
    "14": {
        "desc": "ติดตั้งอุปกรณ์ชุด CONTROL CAP ไม่ใช้เพลท STOCK",
        "price": 500
    },
    "15": {
        "desc": "วายริ่งชุด CONTROL CAP (PFC) 6 STEP",
        "price": 500
    },
    "16": {
        "desc": "วายริ่งชุด CONTROL CAP (PFC) 8 STEP",
        "price": 500
    },
    "17": {
        "desc": "วายริ่งชุด CONTROL CAP (PFC) 10 STEP",
        "price": 500
    },
    "18": {
        "desc": "วายริ่งชุด CONTROL CAP (PFC) 12 STEP",
        "price": 500
    },
    "19": {
        "desc": "วายริ่งชุด CONTROL CAP 6 STEP AUTO ไม่มี PUSH BUTTON",
        "price": 500
    },
    "20": {
        "desc": "วายริ่งชุด CONTROL CAP 12 STEP AUTO ไม่มี PUSH BUTTON",
        "price": 500
    },
    "21": {
        "desc": "ติดตั้งและวายริ่งพัดลม 1 ตัว + THERMOSTAT",
        "price": 500
    },
    "22": {
        "desc": "ติดตั้งและวายริ่งพัดลม 2 ตัว + THERMOSTAT",
        "price": 500
    },
    "23": {
        "desc": "ติดตั้งและวายริ่งชุด CONTROL ATS'ONEC'(MCCB)",
        "price": 500
    },
    "24": {
        "desc": "ติดตั้งและวายริ่งชุด CONTROL ATS'ONEC'(ACB)",
        "price": 500
    },
    "25": {
        "desc": "ติดตั้งและวายริ่งชุด CONTROL ATS'UA'(MCCB)",
        "price": 500
    },
    "26": {
        "desc": "ติดตั้งและวายริ่งชุด CONTROL ATS'UA'(ACB)",
        "price": 500
    },
    "27": {
        "desc": "วายริ่งชุด ACCESSORIES(UV,ST,CC,MOTOR)",
        "price": 500
    },
    "28": {
        "desc": "วายริ่งชุด FUNCTION CB MAIN(OV+UV+TR TEMP+ALARM)",
        "price": 500
    },
    "29": {
        "desc": "วายริ่งชุด GROUND FAULT(MG)",
        "price": 500
    },
    "30": {
        "desc": "ติดตั้งและวายริ่งชุด INTER LOCK 2 MAIN TIE(ACB)",
        "price": 500
    },
    "31": {
        "desc": "วายริ่งชุด MTS(MECHANICAL INTERLOCK)",
        "price": 500
    },
    "32": {
        "desc": "ติดตั้งอุปกรณ์ชุด STARTER DOL 0-40HP",
        "price": 500
    },
    "33": {
        "desc": "ติดตั้งอุปกรณ์ชุด STARTER DOL 50-100HP",
        "price": 500
    },
    "34": {
        "desc": "ติดตั้งอุปกรณ์ชุด STARTER DOL 125-220HP",
        "price": 500
    },
    "35": {
        "desc": "เดินสาย POWER ชุด STARTER DOL 0-40HP",
        "price": 500
    },
    "36": {
        "desc": "เดินสาย POWER ชุด STARTER DOL 50-100HP",
        "price": 500
    },
    "37": {
        "desc": "เดินสาย POWER ชุด STARTER DOL 125-220HP",
        "price": 500
    },
    "38": {
        "desc": "วายริ่งชุด CONTROL STARTER DOL",
        "price": 500
    },
    "39": {
        "desc": "ติดตั้งอุปกรณ์ชุด STARTER STAR-DELTA 0-40HP",
        "price": 500
    },
    "40": {
        "desc": "ติดตั้งอุปกรณ์ชุด STARTER STAR-DELTA 50-100HP",
        "price": 500
    },
    "41": {
        "desc": "ติดตั้งอุปกรณ์ชุด STARTER STAR-DELTA 125-220HP",
        "price": 500
    },
    "42": {
        "desc": "เดินสาย POWER STARTER STAR-DELTA ชุด 0-20HP",
        "price": 500
    },
    "43": {
        "desc": "เดินสาย POWER STARTER STAR-DELTA ชุด 20-40HP",
        "price": 500
    },
    "44": {
        "desc": "เดินสาย POWER STARTER STAR-DELTA ชุด 50-100HP",
        "price": 500
    },
    "45": {
        "desc": "เดินสาย POWER STARTER STAR-DELTA ชุด 125-220HP",
        "price": 500
    },
    "46": {
        "desc": "วายริ่งชุด CONTROL STARTER STAR-DELTA",
        "price": 500
    },
    "47": {
        "desc": "วายริ่ง CONTROL RELAY 1 ชุด",
        "price": 500
    },
    "48": {
        "desc": "วายริ่งชุด HI LEVEL+LOW LEVEL+BUZZER",
        "price": 500
    },
    "49": {
        "desc": "ติดตั้งและวายริ่ง FLOATLESS LEVEL SWITCH 1 บ่อ",
        "price": 500
    },
    "50": {
        "desc": "ติดตั้งและวายริ่ง FLOATLESS LEVEL SWITCH 2 บ่อ",
        "price": 500
    },
    "51": {
        "desc": "ติดตั้งและวายริ่ง TRANSFORMER (แบบตัวเล็กใช้กับชุด PUMP)",
        "price": 500
    },
    "52": {
        "desc": "ติดตั้งสาย G ของ CAP",
        "price": 500
    },
    "53": {
        "desc": "ตั้งขา CB 1 ตัว",
        "price": 500
    },
    "54": {
        "desc": "LIMIT SWITCH",
        "price": 500
    },
    "55": {
        "desc": "FLUORESCENT",
        "price": 500
    },
    "56": {
        "desc": "STARTER WITH REMOTE (ราคาคิดเป็นชุด)",
        "price": 500
    },
    "57": {
        "desc": "ประกอบ CAP(MG)(ประกอบ CAP)",
        "price": 500
    },
    "58": {
        "desc": "ประกอบ MOTOR DRIVE(ของ MCCB&ACB)",
        "price": 500
    },
    "59": {
        "desc": "ติดตั้ง UV-ST-CC",
        "price": 500
    },
    "60": {
        "desc": "ติดตั้ง KEY SWITCH",
        "price": 500
    },
    "61": {
        "desc": "WIRING SQUARE LAMP 0-6 EA",
        "price": 500
    },
    "62": {
        "desc": "WIRING SQUARE LAMP 7-12 EA",
        "price": 500
    },
    "63": {
        "desc": "WIRING CTT8+PLUG(BLOKSET)",
        "price": 500
    },
    "64": {
        "desc": "WIRING CONTROL VSD",
        "price": 500
    },
    "65": {
        "desc": "เดินสาย POWER VSD\/ 1 ชุด(CB-VSD-LOAD) 0-50HP",
        "price": 500
    },
    "66": {
        "desc": "เดินสาย POWER VSD\/ 1 ชุด(CB-VSD-LOAD) 51-100HP",
        "price": 500
    },
    "67": {
        "desc": "ติดตั้ง VSD\/ 1 ชุด",
        "price": 500
    },
    "68": {
        "desc": "WIRING SEPAM BLOKSET\/ ชุด(BLOKSET)",
        "price": 500
    },
    "69": {
        "desc": "WIRING PLUG TERMINAL\/ จุด(BLOKSET)",
        "price": 500
    },
    "70": {
        "desc": "WIRING PLC ต่อ 1 SLOT",
        "price": 500
    },
    "71": {
        "desc": "WIRING SMART RELAY 1 ตัว",
        "price": 500
    },
    "72": {
        "desc": "ติดตั้งและเดินเต้ารับ",
        "price": 500
    },
    "73": {
        "desc": "ใส่คานเลดเดอร์(ต่อ 1 ชิ้น)",
        "price": 500
    },
    "74": {
        "desc": "ติดตั้งฝาหลัง,ฝาข้าง+กุญแจต่างๆ+สติ๊กเกอร์ต่อ 1 ฝา(ยึดน็อต)",
        "price": 500
    },
    "75": {
        "desc": "ติดตั้งฝาหลัง,ฝาข้าง+กุญแจต่างๆ+สติ๊กเกอร์ต่อ 1 ฝา(หัวเรือญี่ปุ่น)",
        "price": 500
    },
    "76": {
        "desc": "ติดตั้งฝาหลัง,ฝาข้าง+กุญแจต่างๆ+สติ๊กเกอร์ต่อ 1 ฝา(เขาควาย)",
        "price": 500
    },
    "77": {
        "desc": "แยกฐานตู้(โครงตู้+ฐานไม่รวมบัสบาร์)",
        "price": 500
    },
    "78": {
        "desc": "ห่อตู้(ต่อ 1 ช่วง)",
        "price": 500
    },
    "79": {
        "desc": "ติดตั้งกระจก",
        "price": 500
    },
    "80": {
        "desc": "ใส่หลังคาพัดลม",
        "price": 500
    },
    "81": {
        "desc": "แยก BUSBAR 0-250A\/ 1 จุด 3 เฟส+SUPPORT",
        "price": 500
    },
    "82": {
        "desc": "แยก BUSBAR 400A\/ 1 จุด 3 เฟส+SUPPORT",
        "price": 500
    },
    "83": {
        "desc": "แยก BUSBAR 630A\/ 1 จุด 3 เฟส+SUPPORT",
        "price": 500
    },
    "84": {
        "desc": "แยก BUSBAR 800A\/ 1 จุด 3 เฟส+SUPPORT",
        "price": 500
    },
    "85": {
        "desc": "แยก BUSBAR 1000A\/ 1 จุด 3 เฟส+SUPPORT",
        "price": 500
    },
    "86": {
        "desc": "แยก BUSBAR 1200A\/ 1 จุด 3 เฟส+SUPPORT",
        "price": 500
    },
    "87": {
        "desc": "แยก BUSBAR 1600A\/ 1 จุด 3 เฟส+SUPPORT",
        "price": 500
    },
    "88": {
        "desc": "แยก BUSBAR 2000A\/ 1 จุด 3 เฟส+SUPPORT",
        "price": 500
    },
    "89": {
        "desc": "แยก BUSBAR 2500A\/ 1 จุด 3 เฟส+SUPPORT",
        "price": 500
    },
    "90": {
        "desc": "แยก BUSBAR 3200A\/ 1 จุด 3 เฟส+SUPPORT",
        "price": 500
    },
    "91": {
        "desc": "แยก BUSBAR 4000A\/ 1 จุด 3 เฟส+SUPPORT",
        "price": 500
    },
    "92": {
        "desc": "แยก BUSBAR 5000A\/ 1 จุด 3 เฟส+SUPPORT",
        "price": 500
    }
};
