<?php
header('Content-Type: application/json; charset=utf-8');

try {
  // รองรับ ping ทดสอบ PHP
  if (isset($_GET['mode']) && $_GET['mode'] === 'ping') {
    echo json_encode(['ok' => true, 'php' => PHP_VERSION]);
    exit;
  }

  // รับ JSON
  $raw = file_get_contents('php://input');
  if ($raw === false) {
    throw new Exception('Cannot read request body');
  }
  $req = json_decode($raw, true);
  if (!is_array($req)) {
    throw new Exception('Invalid JSON body');
  }

  $which = $req['which'] ?? null;
  $data  = $req['data']  ?? null;

  if (!in_array($which, ['pw', 'ct'], true)) {
    throw new Exception('Invalid "which" (pw|ct)');
  }
  if (!is_array($data)) {
    throw new Exception('Invalid "data" (must be object/map)');
  }

  // เตรียมไฟล์และเนื้อหา
  $stamp  = gmdate('c');
  $header = "// Generated by save-db.php on {$stamp}\n";
  if ($which === 'pw') {
    $file = __DIR__ . DIRECTORY_SEPARATOR . 'DatabasePW.js';
    $code = $header . 'var powerDatabase = ' . json_encode($data, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT) . ";\n";
  } else {
    $file = __DIR__ . DIRECTORY_SEPARATOR . 'DatabaseCT.js';
    $code = $header . 'var controlDatabase = ' . json_encode($data, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT) . ";\n";
  }

  // ตรวจสิทธิ์โฟลเดอร์
  if (!is_writable(__DIR__)) {
    throw new Exception('Folder is not writable: ' . __DIR__);
  }

  // เขียนไฟล์ (lock ป้องกันชนกัน)
  $bytes = @file_put_contents($file, $code, LOCK_EX);
  if ($bytes === false) {
    throw new Exception('Cannot write file: ' . basename($file) . ' (check folder permissions)');
  }

  // อัปเดตตัวเลข version.txt เพื่อ cache-busting
  $verFile = __DIR__ . DIRECTORY_SEPARATOR . 'version.txt';
  @file_put_contents($verFile, (string)time(), LOCK_EX);

  echo json_encode(['success' => true, 'file' => basename($file), 'bytes' => $bytes]);
} catch (Exception $e) {
  http_response_code(400);
  echo json_encode(['success' => false, 'error' => $e->getMessage()]);
}
